display_name: UI Pretrain Manager
package_name: scrcpygui
maintainer:
  name: pizi-0
  email: hafizirahim92@gmail.com
priority: optional
section: x11
installed_size: 69420
essential: false
icon: assets/logo.png

dependencies:
  - libayatana-appindicator3.so.1
  - libayatana-indicator3.so.7
  - libayatana-ido3-0.4.so.0
  - libdbusmenu-glib.so.4

postinstall_scripts:
  - echo "UI Pretrain Manager installed successfully"
postuninstall_scripts:
  - echo "UI Pretrain Manager uninstalled successfully"

keywords:
  - scrcpy
  - gui

generic_name: UI Pretrain Manager

categories:
  - Utility

startup_notify: true